[build]
  command = "remix build"
  publish = "public"

[build.environment]
  DEFAULT_BABY_ID = "jfLdOvMT5o73TZigbFOG"
[context.deploy-preview.environment]
  DEFAULT_BABY_ID = "RPNkAF7syRNliNfrgUED"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
