[build]
  command = "npm build"
  publish = "public"

[dev]
  command = "remix watch"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"

[context.production.environment]
  DEFAULT_BABY_ID = "jfLdOvMT5o73TZigbFOG"

[context.develop]
  command = "npm build && echo \"built on develop, default baby id is $DEFAULT_BABY_ID \""

[context.develop.environment]
  DEFAULT_BABY_ID = "RPNkAF7syRNliNfrgUED"